### PR TITLE
Create LICENSE.md

### PR DESCRIPTION
**Pull request by Eisfunke**
Add Creative Commons Attribute-NonCommercial-NoDerivatives as license

### CODE REVIEW

**Comment by Eisfunke** [comment]
See Issue #7

**Comment by Scosh** [comment]
I would prefer a 'plaintext' LICENSE file without a specified extension, as this would conform with the best-practice standards I am aware of.

See an older repository of mine [with a 3.0 CC license](https://github.com/Scosh/Makepkg-Not-War-Wallpaper-Series/blob/master/LICENSE).

This kind of 'clean' but still plaintext style of formatting is sort of the best of both worlds.

Examples for repositories with extension-less LICENSE files:
1. https://github.com/Shougo/deoplete.nvim
2. https://github.com/ellipticaldoor/dfiid
3. https://github.com/vimwiki/vimwiki
4. https://github.com/nteract/nteract

Another way to do it that I've seen is `LICENSE.txt`, but this is not desirable in my opinion.

**Comment by Eisfunke** [comment]
I am aware that most of the time extension-less `LICENSE`-Files are used.
However, as you can see [here](https://help.github.com/articles/adding-a-license-to-a-repository/), GitHub itself recommends using either `LICENSE` *or* `LICENSE.md` as license file. Because the latter goes well with the naming scheme of `README.md` and I like Markdown more than plain text in general, I prefer to use `LICENSE.md` over just `LICENSE`.

That was my reasoning for using `LICENSE.md`. If you prefer `LICENSE` anyway, I will of course edit this PR :wink:

**Comment by Scosh** [comment]
Alrighty-dokes, you make a good point. Especially viewing the Markdown license file on GitHub is pretty convenient. Let's go with Markdown for this one.

**Pull request merged**
